In [1]:
#importing functions

import import_ipynb      #for importing other files in jupyter
import mylibrary as ml   #for accessing library
import numpy as np       #loading files

importing Jupyter notebook from mylibrary.ipynb


In [2]:
#loading files

A = np.loadtxt('q1.csv', delimiter = ',')
b = np.loadtxt('q1_1.csv', delimiter = ',')
b = ml.Matrix_operations.make_proper_column(b)
print(A)

[[ 1.  0.  1.  2.]
 [ 0.  1. -2.  0.]
 [ 1.  2. -1.  0.]
 [ 2.  1.  3. -2.]]


In [3]:
#Printing equations

ml.Printing.print_eq(A, b)



#Solving using dolittle method

x = ml.LU.solve_dolittle(A, b)
print("Using dolittle")
ml.Printing.print_sol(x)



#Solving using crout method

x = ml.LU.solve_crout(A, b)
print("Using crout")
ml.Printing.print_sol(x)

The given equations are:


1.0 x +  0.0 y +  1.0 z +  2.0 w =  6.0
0.0 x +  1.0 y +  -2.0 z +  0.0 w =  -3.0
1.0 x +  2.0 y +  -1.0 z +  0.0 w =  -2.0
2.0 x +  1.0 y +  3.0 z +  -2.0 w =  0.0


Using dolittle
The solutions are:


x  =  1.0
y  =  -1.0
z  =  1.0
w  =  2.0


Using crout
The solutions are:


x  =  1.0
y  =  -1.0
z  =  1.0
w  =  2.0


